# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.TextField(default='aaaa', max_length=150, verbose_name='ツイート内容'),
            preserve_default=False,
        ),
    ]
