# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='profile_image_url_https',
            field=models.CharField(max_length=500, verbose_name='アイコン画像'),
        ),
    ]
