# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_tweet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigIntegerField(unique=True, verbose_name='ツイートID'),
        ),
    ]
