# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 04:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20160917_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccesstoken',
            name='screen_name',
            field=models.CharField(default=datetime.datetime(2016, 9, 17, 4, 26, 46, 588720, tzinfo=utc), max_length=100, verbose_name='Screen name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitteraccesstoken',
            name='user_id',
            field=models.CharField(default=1, max_length=20, verbose_name='User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitteraccesstoken',
            name='x_auth_expires',
            field=models.IntegerField(default=2, verbose_name='有効期限'),
            preserve_default=False,
        ),
    ]
