# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20160917_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboEntryCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=20, verbose_name='先生')),
                ('entry_count', models.IntegerField(verbose_name='登録者数')),
            ],
        ),
    ]
