# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_laboentrycount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboRssItemCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='登録された回数')),
            ],
        ),
    ]
